#!/bin/bash

RED="\e[33m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

echo ""
echo -e "${RED} ######################################################### ${ENDCOLOR}"
echo -e "${RED} #                                                       # ${ENDCOLOR}"
echo -e "${RED} #                   IMPORTANT NOTICE:                   # ${ENDCOLOR}"
echo -e "${RED} #      IF YOU HAVE PAID ANY FORM OF MONEY FOR THIS      # ${ENDCOLOR}"
echo -e "${RED} #     OR ANY OTHER TEAM PIXEL NOSTALGIA / RGS BUILD     # ${ENDCOLOR}"
echo -e "${RED} #                DEMAND YOUR MONEY BACK!                # ${ENDCOLOR}"
echo -e "${RED} #                                                       # ${ENDCOLOR}"
echo -e "${RED} #         THIS BUILD IS FREELY AVAILABLE TO ALL         # ${ENDCOLOR}"
echo -e "${RED} #                VIA OUR DISCORD SERVER:                # ${ENDCOLOR}"
echo -e "${RED} #                                                       # ${ENDCOLOR}"
echo -e "${RED} #             https://discord.gg/xNxrAr6sGv             # ${ENDCOLOR}"
echo -e "${RED} #                                                       # ${ENDCOLOR}"
echo -e "${RED} ######################################################### ${ENDCOLOR}"
echo ""

echo -e "Upgrading Bios....."
sleep 3
/userdata/system/rgs/rclone sync PixN-Themes-New:/update/Batocera/bios /userdata/bios --progress --skip-links


echo -e "Upgrading themes....."
sleep 1

if [ -d "/userdata/themes/ckau-book-PixN" ]; then
    echo -e "upgrade ckau-book-PixN theme"
    /userdata/system/rgs/rclone sync PixN-Themes-New:/update/Themes/ckau-book-PixN /userdata/themes/ckau-book-PixN --progress
fi

if [ -d "/userdata/themes/Hypermax-Plus-PixN" ]; then
    echo -e "upgrade Hypermax-Plus-PixN theme"
    /userdata/system/rgs/rclone sync PixN-Themes-New:/update/Themes/Hypermax-Plus-PixN /userdata/themes/Hypermax-Plus-PixN --exclude=/_inc/videos/** --progress
fi

if [ -d "/userdata/themes/Carbon-PixN" ]; then
    echo -e "upgrade Carbon-PixN theme"
    /userdata/system/rgs/rclone sync PixN-Themes-New:/update/Themes/Carbon-PixN /userdata/themes/Carbon-PixN --progress
fi

if [ -d "/userdata/themes/ckau-book" ]; then
    echo -e "upgrade ckau-book theme"
    /userdata/system/rgs/rclone sync PixN-Themes-New:/update/Themes/ckau-book /userdata/themes/ckau-book --progress
fi


if [ -f "/userdata/roms/clonehero/gamelist.xml" ]; then
    echo -e "upgrade clonehero videos"
    /userdata/system/rgs/rclone sync PixN-Themes-New:/update/Batocera/clonehero/Custom /userdata/system/.clonehero/Custom --progress
fi

echo -e "Upgrading bezels....."
sleep 1

if [ -f "/userdata/roms/vectrex/gamelist.xml" ]; then
    echo -e "upgrade vectrex bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/vectrex /userdata/decorations/mybezels16-9/games/vectrex --progress --ignore-existing
fi

if [ -f "/userdata/roms/neogeo/gamelist.xml" ]; then
    echo -e "upgrade neogeo bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/neogeo /userdata/decorations/mybezels16-9/games/neogeo --progress --ignore-existing
fi

if [ -f "/userdata/roms/mame/gamelist.xml" ]; then
    echo -e "upgrade mame bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/mame /userdata/decorations/mybezels16-9/games/mame --progress --ignore-existing
fi

if [ -f "/userdata/roms/fbneo/gamelist.xml" ]; then
    echo -e "upgrade fbneo bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/fbneo /userdata/decorations/mybezels16-9/games/fbneo --progress --ignore-existing
fi

if [ -f "/userdata/roms/cps1/gamelist.xml" ]; then
    echo -e "upgrade cps1 bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/cps1 /userdata/decorations/mybezels16-9/games/cps1 --progress --ignore-existing
fi

if [ -f "/userdata/roms/cps2/gamelist.xml" ]; then
    echo -e "upgrade cps2 bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/cps2 /userdata/decorations/mybezels16-9/games/cps2 --progress --ignore-existing
fi

if [ -f "/userdata/roms/cps3/gamelist.xml" ]; then
    echo -e "upgrade cps3 bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/cps3 /userdata/decorations/mybezels16-9/games/cps3 --progress --ignore-existing
fi

if [ -f "/userdata/roms/naomi/gamelist.xml" ]; then
    echo -e "upgrade naomi bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/naomi /userdata/decorations/mybezels16-9/games/naomi --progress --ignore-existing
fi

if [ -f "/userdata/roms/naomi2/gamelist.xml" ]; then
    echo -e "upgrade naomi2 bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/naomi2 /userdata/decorations/mybezels16-9/games/naomi2 --progress --ignore-existing
fi

if [ -f "/userdata/roms/igspgm/gamelist.xml" ]; then
    echo -e "upgrade igspgm bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/igspgm /userdata/decorations/mybezels16-9/games/igspgm --progress --ignore-existing
fi

if [ -f "/userdata/roms/intellivision/gamelist.xml" ]; then
    echo -e "upgrade intellivision bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/intellivision /userdata/decorations/mybezels16-9/games/intellivision --progress --ignore-existing
fi

if [ -f "/userdata/roms/gaelco/gamelist.xml" ]; then
    echo -e "upgrade gaelco bezels"
    /userdata/system/rgs/rclone copy PixN-Themes-New:/update/decorations/mybezels16-9/games/gaelco /userdata/decorations/mybezels16-9/games/gaelco --progress --ignore-existing
fi
