#!/bin/bash

ARCHIVE="update.tar.gz"
ARCHIVEPATH="/userdata/extractions/$ARCHIVE"

#read user configuration before "RGS TUNING", for user system changes
BEGINCONF=$(sed -e '/RGS TUNING/,$d' /userdata/system/batocera.conf)

#read end user conf after "END RGS".  (or jupace.emulator for v39 initial release)
if grep -q "END RGS" /userdata/system/batocera.conf; then
    ENDCONF=$(sed -e '0,/END RGS/d' /userdata/system/batocera.conf)
else
    ENDCONF=$(sed -e '0,/jupace.emulator/d' /userdata/system/batocera.conf)
fi

#download pack
echo "Downloading new files..."
wget --progress=dot:binary --no-check-certificate --no-cache --no-cookies -O $ARCHIVEPATH "https://rgsretro1986.ds78102.seedhost.eu/update/v40/update.tar.gz"
tar -xvzf $ARCHIVEPATH --directory /userdata/
rm $ARCHIVEPATH


#read new conf after 'RGS TUNING' , for games tuning
RGSTUNING=$(sed -n '/RGS TUNING/,/END RGS/p' /userdata/system/batocera.conf)


echo "Update batocera.conf"


echo "$BEGINCONF" > /userdata/system/batocera.conf.new
echo "$RGSTUNING" >> /userdata/system/batocera.conf.new
echo "$ENDCONF" >> /userdata/system/batocera.conf.new
mv /userdata/system/batocera.conf.new /userdata/system/batocera.conf

echo "Update settings"

sed -i 's/ckau-book-rgs-v2/ckau-book-PixN/' /userdata/system/configs/emulationstation/es_settings.cfg
sed -i 's/name="SaveGamelistsOnExit" value="false"/name="SaveGamelistsOnExit" value="true"/' /userdata/system/configs/emulationstation/es_settings.cfg
echo 'Deleting old files'

rm themes/Hypermax-Plus-PixN/Gamelist-text anim.xml
rm themes/Hypermax-Plus-PixN/_inc/logos/bk.rar
rm themes/Hypermax-Plus-PixN/_inc/logos/electronika.png
rm themes/Hypermax-Plus-PixN/_inc/scotty.mp4
rm "themes/Hypermax-Plus-PixN/_inc/text anim/*"
rm themes/Hypermax-Plus-PixN/_inc/wallpaper1/desktop.ini
rm themes/Hypermax-Plus-PixN/_template/4815203235791361221411321768176177154196199443.ico
rm themes/Hypermax-Plus-PixN/default/desktop.ini
rm themes/Hypermax-Plus-PixN/konami/desktop.ini
echo 'Upgrade finished. Emulationstation will be reloaded.'
sleep 2
killall -9 emulationstation
