#!/bin/bash

if [ -f "/userdata/system/rgs.version" ]; then
    CURRENTRGSVERSION=$(cat /userdata/system/rgs.version)
else
    CURRENTRGSVERSION="0"
fi

if [[ "$CURRENTRGSVERSION" =~ ^40 ]]; then
    echo "version: 40"
    ARCHIVE="v40tov41update.tar.gz"
elif [[ "$CURRENTRGSVERSION" =~ ^41 ]]; then
    echo "version: 41"
    ARCHIVE="update.tar.gz"
else
   echo "wrong version"
   exit 1
fi

ARCHIVEPATH="/userdata/extractions/$ARCHIVE"

#read user configuration before "RGS TUNING", for user system changes
BEGINCONF=$(sed -e '/RGS TUNING/,$d' /userdata/system/batocera.conf)

#read end user conf after "END RGS".  (or jupace.emulator for v39 initial release)
if grep -q "END RGS" /userdata/system/batocera.conf; then
    ENDCONF=$(sed -e '0,/END RGS/d' /userdata/system/batocera.conf)
else
    ENDCONF=$(sed -e '0,/jupace.emulator/d' /userdata/system/batocera.conf)
fi


#download pack
echo "Downloading new files..."
wget --progress=dot:binary --no-check-certificate --no-cache --no-cookies -O $ARCHIVEPATH "http://rgsretro1986.ds78102.seedhost.eu/update/v41/$ARCHIVE"


if [[ "$CURRENTRGSVERSION" =~ ^40 ]]; then
    echo 'Deleting old files from v40'

    rm -rf /userdata/system/evmapy
    rm -rf /userdata/bios/switch/*
    rm -rf /userdata/system/switch/*
    rm -rf /userdata/system/configs/Ryujinx/bis/system/Contents/registered
    rm -rf /userdata/system/configs/yuzu/nand/system/Contents/registered
    rm -rf /userdata/system/wine/*
    rm /userdata/system/configs/3dsen/GeneratorImporter.py
    rm /userdata/system/configs/3dsen/launcher.py
    rm -rf /userdata/system/configs/Ryujinx/system
    rm /userdata/system/configs/demul/GeneratorImporter.py
    rm /userdata/system/configs/demul/__pycache__/GeneratorImporter.cpython-311.pyc
    rm /userdata/system/configs/demul/__pycache__/customGenerator.cpython-311.pyc
    rm /userdata/system/configs/demul/demul/gpuDX11old.ini
    rm /userdata/system/configs/demul/launcher.py
    rm /userdata/system/configs/dolphin5-triforce/GeneratorImporter.py
    rm /userdata/system/configs/dolphin5-triforce/launcher.py
    rm /userdata/system/configs/gaelco/Demul.ini
    rm /userdata/system/configs/gaelco/GeneratorImporter.py
    rm /userdata/system/configs/gaelco/gpuDX11old.ini
    rm /userdata/system/configs/gaelco/launcher.py
    rm /userdata/system/configs/gaelco/launcher.py.save
    rm /userdata/system/configs/sudachi
    rm /userdata/system/configs/winebat/GeneratorImporter.py
    rm /userdata/system/configs/winebat/launcher.py
    rm '/userdata/themes/Carbon-PixN/art/logos/atari.svg'
    rm '/userdata/themes/Hypermax-Plus-PixN/Gamelist-text anim.xml'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/logos/CloneHero.jpg'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/logos/bk.rar'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/logos/electronika.png'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/music/Beach (8-Bit Remix) - New Super Mario Bros.ogg'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/music/Fracktail Battle (8-Bit Cover) - Super Paper Mario.ogg'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/music/Francis Battle 8Bit Remix  Super Paper Mario BT.ogg'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/music/Mars Attacks Main Theme.mp3'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/music/Mars Attacks Main Theme.wav'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/music/New Super Mario Bros.ogg'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/music/Red Streamer Battle (8-Bit Remix) - Paper Mario_ The Origami King.ogg'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/music/Vellumental Battle 8Bit Remix  Paper Mario The Origami King.ogg'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/scotty.mp4'
    rm -rf themes/Hypermax-Plus-PixN/_inc/text anim/*
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/wallpaper1/D0IIRGVUcAEcS5K.png'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/wallpaper1/NINTCHDBPICT000536074229-e1572807808559.webp'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/wallpaper1/desktop.ini'
    rm '/userdata/themes/Hypermax-Plus-PixN/_inc/wallpaper1/neshd.png'
    rm '/userdata/themes/Hypermax-Plus-PixN/_template/4815203235791361221411321768176177154196199443.ico'
    rm '/userdata/themes/Hypermax-Plus-PixN/capcom/desktop.ini'
    rm '/userdata/themes/Hypermax-Plus-PixN/default/desktop.ini'
    rm '/userdata/themes/Hypermax-Plus-PixN/konami/desktop.ini'
else
    echo 'Deleting old files'

    rm -rf /userdata/system/switch/extra
    rm -rf /userdata/system/switch/logs
    rm /userdata/system/switch/Ryujinx-Avalonia.AppImage
    rm /userdata/system/switch/yuzuEA.AppImage
    rm /userdata/system/switch/CONFIG.txt
    rm /userdata/system/switch/Ryujinx-LDN.AppImage
    rm /userdata/system/switch/Ryujinx-Avalonia.AppImage
    rm /userdata/system/switch/configgen/GeneratorImporter.py
    rm /userdata/system/switch/configgen/switchlauncher2.py
    rm /userdata/system/switch/configgen/switchlauncher.py
    rm /userdata/system/switch/switch/configgen/generators/Generator.py
    rm /userdata/system/configs/emulationstation/es_systems_atarijaguarcd.cfg
    rm /userdata/system/configs/evmapy/model3.keys
    rm /usr/share/applications/Ryujinx.desktop
    rm /usr/share/applications/yuzu.desktop
    rm /userdata/system/switch/Ryujinx.desktop
    rm /userdata/system/switch/yuzu.desktop
    rm /userdata/system/configs/emulationstation/es_systems_gc-jp.cfg
    rm /userdata/system/configs/emulationstation/es_systems_gch.cfg
    rm system/configs/emulationstation/es_systems_lindbergh.cfg
    rm /userdata/bio/switch/keys/title.keys_autogenerated
    rm /userdata/saves/mame/mame/cfg/alien3.cfg
    rm /userdata/saves/mame/mame/cfg/area51.cfg
    rm /userdata/saves/mame/mame/cfg/bang.cfg
    rm /userdata/saves/mame/mame/cfg/bbh.cfg
    rm /userdata/saves/mame/mame/cfg/bbh2sp.cfg
    rm /userdata/saves/mame/mame/cfg/bbhcotw.cfg
    rm /userdata/saves/mame/mame/cfg/bbhsc.cfg
    rm /userdata/saves/mame/mame/cfg/bbust2.cfg
    rm /userdata/saves/mame/mame/cfg/bbusters.cfg
    rm /userdata/saves/mame/mame/cfg/borntofi.cfg
    rm /userdata/saves/mame/mame/cfg/bronx.cfg
    rm /userdata/saves/mame/mame/cfg/bubbletr.cfg
    rm /userdata/saves/mame/mame/cfg/carnevil.cfg
    rm /userdata/saves/mame/mame/cfg/carnking.cfg
    rm /userdata/saves/mame/mame/cfg/cheyenne.cfg
    rm /userdata/saves/mame/mame/cfg/chiller.cfg
    rm /userdata/saves/mame/mame/cfg/claybust.cfg
    rm /userdata/saves/mame/mame/cfg/claypign.cfg
    rm /userdata/saves/mame/mame/cfg/combat.cfg
    rm /userdata/saves/mame/mame/cfg/combh.cfg
    rm /userdata/saves/mame/mame/cfg/cracksht.cfg
    rm /userdata/saves/mame/mame/cfg/critcrsh.cfg
    rm /userdata/saves/mame/mame/cfg/crossbow.cfg
    rm /userdata/saves/mame/mame/cfg/cryptklr.cfg
    rm /userdata/saves/mame/mame/cfg/cyclshtg.cfg
    rm /userdata/saves/mame/mame/cfg/deerhunt.cfg
    rm /userdata/saves/mame/mame/cfg/desertgu.cfg
    rm /userdata/saves/mame/mame/cfg/dragngun.cfg
    rm /userdata/saves/mame/mame/cfg/duckhunt.cfg
    rm /userdata/saves/mame/mame/cfg/eggventr.cfg
    rm /userdata/saves/mame/mame/cfg/evilngt.cfg
    rm /userdata/saves/mame/mame/cfg/g13knd.cfg
    rm /userdata/saves/mame/mame/cfg/gdfs.cfg
    rm /userdata/saves/mame/mame/cfg/ghlpanic.cfg
    rm /userdata/saves/mame/mame/cfg/golgo13.cfg
    rm /userdata/saves/mame/mame/cfg/gollygho.cfg
    rm /userdata/saves/mame/mame/cfg/gotcha.cfg
    rm /userdata/saves/mame/mame/cfg/greatgun.cfg
    rm /userdata/saves/mame/mame/cfg/gunbustr.cfg
    rm /userdata/saves/mame/mame/cfg/gunchamp.cfg
    rm /userdata/saves/mame/mame/cfg/hellngt.cfg
    rm /userdata/saves/mame/mame/cfg/hitnmiss.cfg
    rm /userdata/saves/mame/mame/cfg/hogalley.cfg
    rm /userdata/saves/mame/mame/cfg/invasnab.cfg
    rm /userdata/saves/mame/mame/cfg/jdredd.cfg
    rm /userdata/saves/mame/mame/cfg/jpark.cfg
    rm /userdata/saves/mame/mame/cfg/le2.cfg
    rm /userdata/saves/mame/mame/cfg/lethalen.cfg
    rm /userdata/saves/mame/mame/cfg/lethalj.cfg
    rm /userdata/saves/mame/mame/cfg/lghost.cfg
    rm /userdata/saves/mame/mame/cfg/loffire.cfg
    rm /userdata/saves/mame/mame/cfg/lordgun.cfg
    rm /userdata/saves/mame/mame/cfg/luckywld.cfg
    rm /userdata/saves/mame/mame/cfg/maxforce.cfg
    rm /userdata/saves/mame/mame/cfg/mechatt.cfg
    rm /userdata/saves/mame/mame/cfg/nstocker.cfg
    rm /userdata/saves/mame/mame/cfg/nycaptor.cfg
    rm /userdata/saves/mame/mame/cfg/oneshot.cfg
    rm /userdata/saves/mame/mame/cfg/optiger.cfg
    rm /userdata/saves/mame/mame/cfg/opwolf.cfg
    rm /userdata/saves/mame/mame/cfg/opwolf3.cfg
    rm /userdata/saves/mame/mame/cfg/othunder.cfg
    rm /userdata/saves/mame/mame/cfg/pc_duckh.cfg
    rm /userdata/saves/mame/mame/cfg/pc_hgaly.cfg
    rm /userdata/saves/mame/mame/cfg/pc_wgnmn.cfg
    rm /userdata/saves/mame/mame/cfg/policetr.cfg
    rm /userdata/saves/mame/mame/cfg/ptblank.cfg
    rm /userdata/saves/mame/mame/cfg/ptblank2.cfg
    rm /userdata/saves/mame/mame/cfg/ptblank3.cfg
    rm /userdata/saves/mame/mame/cfg/rapidfir.cfg
    rm /userdata/saves/mame/mame/cfg/rchase.cfg
    rm /userdata/saves/mame/mame/cfg/revx.cfg
    rm /userdata/saves/mame/mame/cfg/sgunner.cfg
    rm /userdata/saves/mame/mame/cfg/sgunner2.cfg
    rm /userdata/saves/mame/mame/cfg/shootgal.cfg
    rm /userdata/saves/mame/mame/cfg/shoottv.cfg
    rm /userdata/saves/mame/mame/cfg/shtngmst.cfg
    rm /userdata/saves/mame/mame/cfg/spacegun.cfg
    rm /userdata/saves/mame/mame/cfg/sshooter.cfg
    rm /userdata/saves/mame/mame/cfg/targeth.cfg
    rm /userdata/saves/mame/mame/cfg/terabrst.cfg
    rm /userdata/saves/mame/mame/cfg/term2.cfg
    rm /userdata/saves/mame/mame/cfg/thunderh.cfg
    rm /userdata/saves/mame/mame/cfg/tickee.cfg
    rm /userdata/saves/mame/mame/cfg/timecris.cfg
    rm /userdata/saves/mame/mame/cfg/timecrs2.cfg
    rm /userdata/saves/mame/mame/cfg/totlvice.cfg
    rm /userdata/saves/mame/mame/cfg/triplhnt.cfg
    rm /userdata/saves/mame/mame/cfg/trophyh.cfg
    rm /userdata/saves/mame/mame/cfg/tshoot.cfg
    rm /userdata/saves/mame/mame/cfg/turkhunt.cfg
    rm /userdata/saves/mame/mame/cfg/tutstomb.cfg
    rm /userdata/saves/mame/mame/cfg/undrfire.cfg
    rm /userdata/saves/mame/mame/cfg/vsfdf.cfg
    rm /userdata/saves/mame/mame/cfg/vsgshoe.cfg
    rm /userdata/saves/mame/mame/cfg/wanted.cfg
    rm /userdata/saves/mame/mame/cfg/whodunit.cfg
    rm /userdata/saves/mame/mame/cfg/wildplt.cfg
    rm /userdata/saves/mame/mame/cfg/wschamp.cfg
    rm /userdata/saves/mame/mame/cfg/zeropnt.cfg
    rm /userdata/saves/mame/mame/cfg/zeropnt2.cfg
    rm /userdata/saves/mame/mame/cfg/zombraid.cfg

fi

tar -xvzf $ARCHIVEPATH --directory /userdata/
rm $ARCHIVEPATH

#workaround lock for v41, to remove in v42
if [[ -f "/userdata/roms/rgs/rgs_upgrade.sh.new" ]]; then
    cp /userdata/roms/rgs/rgs_upgrade.sh.new /userdata/roms/rgs/rgs_upgrade.sh
    rm /userdata/roms/rgs/rgs_upgrade.sh.new
fi

#read new conf after 'RGS TUNING' , for games tuning
RGSTUNING=$(sed -n '/RGS TUNING/,/END RGS/p' /userdata/system/batocera.conf)


echo "Update batocera.conf"

echo "$BEGINCONF" > /userdata/system/batocera.conf.new

#sed -i '/system.services/d' /userdata/system/batocera.conf.new
sed -i '/windows.dxvk/d' /userdata/system/batocera.conf.new
sed -i '/windows.fsync/d' /userdata/system/batocera.conf.new
sed -i '/windows.esync/d' /userdata/system/batocera.conf.new

echo "$RGSTUNING" >> /userdata/system/batocera.conf.new
echo "$ENDCONF" >> /userdata/system/batocera.conf.new
mv /userdata/system/batocera.conf.new /userdata/system/batocera.conf

/usr/bin/batocera-services enable rgs_config

echo "Update settings"

sed -i 's/ckau-book-rgs-v2/ckau-book-PixN/' /userdata/system/configs/emulationstation/es_settings.cfg
sed -i 's/name="SaveGamelistsOnExit" value="false"/name="SaveGamelistsOnExit" value="true"/' /userdata/system/configs/emulationstation/es_settings.cfg

if ! grep -q "datach.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"datach.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "sega32xcd.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"sega32xcd.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "sega32x.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"sega32x.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "megacd.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"megacd.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "megacd32x.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"megacd32x.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "genesis.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"genesis.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "genh.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"genh.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "clonehero.FolderViewMode" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"clonehero.FolderViewMode\" value=\"never\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "2players,4players" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '/CollectionSystemsAuto/c\\\\t<string name="CollectionSystemsAuto" value="favorites,lightgun,recent,wheel" />' /userdata/system/configs/emulationstation/es_settings.cfg
    sed -i '/CollectionSystemsCustom/c\\\\t<string name="CollectionSystemsCustom" value="3players,4players,arcade-classics,arcade-killer,beatemup,fighting,platform,puzzle,run-and-gun,shumps-horizontal,shumps-vertical,sports" />' /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "gamecube-jp.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"gamecube-jp.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "gamecubeh.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"gamecubeh.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if ! grep -q "clonehero.ungroup" /userdata/system/configs/emulationstation/es_settings.cfg; then
    sed -i '$i'"$(echo "\\\t<bool name=\"clonehero.ungroup\" value=\"true\" />")" /userdata/system/configs/emulationstation/es_settings.cfg
fi

if [[ "$CURRENTRGSVERSION" =~ ^40 ]]; then
    echo 'RGS Upgrade from v40 to v41 finished. The system will reboot.'
    sleep 5
    reboot
else
    echo 'Upgrade finished. Emulationstation will be reloaded.'
    sleep 5
    killall -9 emulationstation
fi
