#!/bin/bash

echo "Upgrading themes....."

if [ -d "/userdata/themes/ckau-book-PixN" ]; then
    echo "upgrade ckau-book-PixN theme"
    /userdata/system/rgsfix/rclone sync PixN-Themes:/ckau-book-PixN /userdata/themes/ckau-book-PixN --progress
fi

if [ -d "/userdata/themes/Hypermax-Plus-PixN" ]; then
    echo "upgrade Hypermax-Plus-PixN theme"
    /userdata/system/rgsfix/rclone sync PixN-Themes:/Hypermax-Plus-PixN /userdata/themes/Hypermax-Plus-PixN --progress
fi

if [ -d "/userdata/themes/Carbon-PixN" ]; then
    echo "upgrade Carbon-PixN theme"
    /userdata/system/rgsfix/rclone sync PixN-Themes:/Carbon-PixN /userdata/themes/Carbon-PixN --progress
fi


