#!/bin/bash

echo "Upgrading themes....."


#curl --silent --output /dev/null https://pixeldrain.com/api/filesystem/pXCC5M4U

if [ -d "/userdata/themes/ckau-book-PixN" ]; then
    echo "upgrade ckau-book-PixN theme"
    /userdata/system/rgsfix/rclone sync PixN-Themes-New:/ckau-book-PixN /userdata/themes/ckau-book-PixN --progress
fi

if [ -d "/userdata/themes/Hypermax-Plus-PixN" ]; then
    echo "upgrade Hypermax-Plus-PixN theme"
    /userdata/system/rgsfix/rclone sync PixN-Themes-New:/Hypermax-Plus-PixN /userdata/themes/Hypermax-Plus-PixN --progress
fi

if [ -d "/userdata/themes/Carbon-PixN" ]; then
    echo "upgrade Carbon-PixN theme"
    /userdata/system/rgsfix/rclone sync PixN-Themes-New:/Carbon-PixN /userdata/themes/Carbon-PixN --progress
fi

if [ -d "/userdata/themes/Hypermax-Lite-PixN" ]; then
    echo "upgrade Hypermax-Lite-PixN theme"
    /userdata/system/rgsfix/rclone sync PixN-Themes-New:/Hypermax-Lite-PixN /userdata/themes/Hypermax-Lite-PixN --progress
fi

if [ -d "/userdata/themes/ckau-book" ]; then
    echo "upgrade ckau-book theme"
    /userdata/system/rgsfix/rclone sync PixN-Themes-New:/ckau-book /userdata/themes/ckau-book --progress
fi


